<?php

/**
 * BaseLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $city_id
 * @property string $name
 * @property City $City
 * @property Doctrine_Collection $Listing
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method integer             getCityId()  Returns the current record's "city_id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method City                getCity()    Returns the current record's "City" value
 * @method Doctrine_Collection getListing() Returns the current record's "Listing" collection
 * @method Location            setId()      Sets the current record's "id" value
 * @method Location            setCityId()  Sets the current record's "city_id" value
 * @method Location            setName()    Sets the current record's "name" value
 * @method Location            setCity()    Sets the current record's "City" value
 * @method Location            setListing() Sets the current record's "Listing" collection
 * 
 * @package    realestate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('location');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('Listing', array(
             'local' => 'id',
             'foreign' => 'location_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($i18n0);
    }
}