<?php

/**
 * BaseTextPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $page_name
 * @property string $content
 * 
 * @method integer  getId()        Returns the current record's "id" value
 * @method varchar  getPageName()  Returns the current record's "page_name" value
 * @method string   getContent()   Returns the current record's "content" value
 * @method TextPage setId()        Sets the current record's "id" value
 * @method TextPage setPageName()  Sets the current record's "page_name" value
 * @method TextPage setContent()   Sets the current record's "content" value
 * 
 * @package    realestate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTextPage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('text_page');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('page_name', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'content',
             ),
             ));
        $this->actAs($i18n0);
    }
}