advertisement:
  class: sfDoctrineRouteCollection
  options:
    model:                Advertisement
    module:               advertisement
    prefix_path:          /advertisement
    column:               id
    with_wildcard_routes: true

messages:
  class: sfDoctrineRouteCollection
  options:
    model:                Messages
    module:               messages
    prefix_path:          /messages
    column:               id
    with_wildcard_routes: true

text_page:
  class: sfDoctrineRouteCollection
  options:
    model:                TextPage
    module:               text_page
    prefix_path:          /text_page
    column:               id
    with_wildcard_routes: true

slider_photos:
  class: sfDoctrineRouteCollection
  options:
    model:                SliderPhotos
    module:               slider_photos
    prefix_path:          /slider_photos
    column:               id
    with_wildcard_routes: true

listing:
  class: sfDoctrineRouteCollection
  options:
    model:                listing
    module:               listing
    prefix_path:          /listing
    column:               id
    with_wildcard_routes: true

news:
  class: sfDoctrineRouteCollection
  options:
    model:                news
    module:               news
    prefix_path:          /news
    column:               id
    with_wildcard_routes: true

text_langues:
  class: sfDoctrineRouteCollection
  options:
    model:                Langues
    module:               text_langues
    prefix_path:          /text/langues
    column:               id
    with_wildcard_routes: true

text_trans:
  class: sfDoctrineRouteCollection
  options:
    model:                transUnit
    module:               text_trans
    prefix_path:          /text/trans
    column:               msg_id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: listing, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
