<?php

/**
 * SliderPhotosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SliderPhotosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SliderPhotosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SliderPhotos');
    }
}