# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

localized_homepage:
  url:   /:sf_culture/
  param: { module: default, action: index }
  requirements:
    sf_culture: (?:en|lv|ru)

product:
  url: /:sf_culture/product/:id
  param: { module: product, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:sf_culture/:module
  param: { action: index }

default:
  url:   /:sf_culture/:module/:action/*
