<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('listing_translation', 'listing_translation_id_listing_id', array(
             'name' => 'listing_translation_id_listing_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'listing',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('news_translation', 'news_translation_id_news_id', array(
             'name' => 'news_translation_id_news_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'news',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('listing_translation', 'listing_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('news_translation', 'news_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('listing_translation', 'listing_translation_id_listing_id');
        $this->dropForeignKey('news_translation', 'news_translation_id_news_id');
        $this->removeIndex('listing_translation', 'listing_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('news_translation', 'news_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}