<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('listing', 'has_photos', 'boolean', '25', array(
             ));
        $this->addColumn('listing', 'has_videos', 'boolean', '25', array(
             ));
        $this->addColumn('listing', 'is_on_map', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('listing', 'has_photos');
        $this->removeColumn('listing', 'has_videos');
        $this->removeColumn('listing', 'is_on_map');
    }
}