<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('property_photos', 'property_photos_listing_id_listing_id', array(
             'name' => 'property_photos_listing_id_listing_id',
             'local' => 'listing_id',
             'foreign' => 'id',
             'foreignTable' => 'listing',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('property_photos', 'property_photos_listing_id', array(
             'fields' => 
             array(
              0 => 'listing_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('property_photos', 'property_photos_listing_id_listing_id');
        $this->removeIndex('property_photos', 'property_photos_listing_id', array(
             'fields' => 
             array(
              0 => 'listing_id',
             ),
             ));
    }
}