<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('listing', 'is_renovated', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->changeColumn('listing', 'is_furnished', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->changeColumn('listing', 'is_active', 'boolean', '25', array(
             'default' => '1',
             ));
        $this->changeColumn('listing_translation', 'month_deal', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {

    }
}