<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version36 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('advert_translation', 'filename');
        $this->removeColumn('advert_translation', 'url');
        $this->addColumn('advert', 'filename', 'string', '', array(
             'notnull' => '1',
             ));
        $this->addColumn('advert', 'url', 'string', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('advert_translation', 'filename', 'string', '', array(
             'notnull' => '1',
             ));
        $this->addColumn('advert_translation', 'url', 'string', '', array(
             'notnull' => '1',
             ));
        $this->removeColumn('advert', 'filename');
        $this->removeColumn('advert', 'url');
    }
}