<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version35 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('advert_translation', 'advert_translation_id_advert_id', array(
             'name' => 'advert_translation_id_advert_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'advert',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('advert_translation', 'advert_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('advert_translation', 'advert_translation_id_advert_id');
        $this->removeIndex('advert_translation', 'advert_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}