<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('messages', 'messages_reply_to_messages_id', array(
             'name' => 'messages_reply_to_messages_id',
             'local' => 'reply_to',
             'foreign' => 'id',
             'foreignTable' => 'messages',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('messages', 'messages_listing_id_listing_id', array(
             'name' => 'messages_listing_id_listing_id',
             'local' => 'listing_id',
             'foreign' => 'id',
             'foreignTable' => 'listing',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('messages', 'messages_reply_to', array(
             'fields' => 
             array(
              0 => 'reply_to',
             ),
             ));
        $this->addIndex('messages', 'messages_listing_id', array(
             'fields' => 
             array(
              0 => 'listing_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('messages', 'messages_reply_to_messages_id');
        $this->dropForeignKey('messages', 'messages_listing_id_listing_id');
        $this->removeIndex('messages', 'messages_reply_to', array(
             'fields' => 
             array(
              0 => 'reply_to',
             ),
             ));
        $this->removeIndex('messages', 'messages_listing_id', array(
             'fields' => 
             array(
              0 => 'listing_id',
             ),
             ));
    }
}