<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('messages', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'reply_to' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '8',
             ),
             'listing_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'message' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'contact' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('messages');
    }
}