<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('listing', 'has_photos');
        $this->removeColumn('listing', 'is_on_map');
        $this->addColumn('listing', 'street', 'string', '', array(
             'notnull' => '1',
             ));
        $this->addColumn('listing', 'land_area', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('listing', 'main_photo', 'string', '', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->addColumn('listing', 'has_photos', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('listing', 'is_on_map', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->removeColumn('listing', 'street');
        $this->removeColumn('listing', 'land_area');
    }
}