<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('advert_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'filename' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'url' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->removeColumn('advert', 'filename');
        $this->removeColumn('advert', 'url');
        $this->removeColumn('advert', 'active');
    }

    public function down()
    {
        $this->dropTable('advert_translation');
        $this->addColumn('advert', 'filename', 'string', '', array(
             'notnull' => '1',
             ));
        $this->addColumn('advert', 'url', 'string', '', array(
             'notnull' => '1',
             ));
        $this->addColumn('advert', 'active', 'boolean', '25', array(
             ));
    }
}