<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version33 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('advert', 'name', 'string', '', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('advert', 'name');
    }
}