<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('listing', 'for_rent', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->changeColumn('listing', 'has_photos', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->changeColumn('listing', 'has_videos', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->changeColumn('listing', 'is_on_map', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {

    }
}