<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('listing', 'is_renovated', 'boolean', '25', array(
             ));
        $this->changeColumn('listing', 'is_furnished', 'boolean', '25', array(
             ));
        $this->changeColumn('listing', 'for_rent', 'boolean', '25', array(
             ));
        $this->changeColumn('listing', 'is_active', 'boolean', '25', array(
             ));
    }

    public function down()
    {

    }
}