<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('listing', 'main_photo', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('listing', 'main_photo');
    }
}