<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('text_pages');
    }

    public function down()
    {
        $this->createTable('text_pages', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'page_name' => 
             array(
              'type' => 'varchar',
              'notnull' => '1',
              'length' => '255',
             ),
             'content' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
    }
}