<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('messages', 'company', 'varchar', '255', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('messages', 'company');
    }
}