<?php

/**
 * City
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    realestate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class City extends BaseCity
{
	static function getAllCities($culture){ //faster than getting all cities through object.
		$cities = Doctrine_Query::create()
				->select('c.id as id, t.name as name')
				->from('City c')
				->leftJoin('c.Translation t')
				->where('t.lang = ?', $culture)
				->orderBy('t.name asc')
				->execute();

		return($cities);
	}
	
	static function getCitiesList($culture){
		foreach(self::getAllCities($culture) as $c){
			$list[$c['id']] = $c['name'];
		}
		
		return $list;
	}
	
	function getCleanName(){
		$name = $this->getName();
		$local_chars = array('Ā', 'ā', 'č', 'Č', 'Ē', 'ē', 'Ī', 'ī', 'Ģ', 'ģ', 'Ņ', 'ņ', 'Š', 'š', 'Ū', 'ū', 'Ž', 'ž', 'Ķ', 'ķ');
		$replaces = array('A', 'a', 'c', 'C', 'E', 'e', 'I', 'i', 'G', 'g', 'N', 'n', 'S', 's', 'U', 'u', 'Z', 'z', 'K', 'k');
		$clean_str = str_replace($local_chars, $replaces, $name);
		return($clean_str);
	}
}