<?php

/**
 * Location
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    realestate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Location extends BaseLocation
{
	static function getAllDistricts($culture){
		$districts = Doctrine_Query::create()
				->select('l.id as id, l.city_id as city_id, t.name as name')
				->from('Location l')
				->leftJoin('l.Translation t')
				->where('t.lang = ?', $culture)
				->orderBy('t.name asc')
				->fetchArray();
		
		return($districts);
	}
	
	static function getDistrictsList($culture){
		//var_dump(self::getAllDistricts('en'));
		foreach(self::getAllDistricts($culture) as $d){
			$list[$d['id']] = $d['name'];
		}
		
		return($list);
	}
}