<?php

/**
 * TextPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TextPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TextPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TextPage');
    }
}